### ISSUE TITLE
how to get the programmed groupadresses in a kdrive datapoint?

### ISSUE THREAD

**Issue by Golpe82** [weinzierl-engineering/baos#10]
Hi,
i am working with a kberry.
i have  3 programmed datapoints in a baos 830 in ETS:
one dpt1 with address 1/2/0
one dpt3 with address 1/2/4
and one dpt5 with address 1/2/3
I would like to read in a c++ programm the groupadresses programmed in each datapoint.
It is possible with the Baos c++ baos api?

thanks!

**Comment by weinzierl-engineering** [comment]
Hi,

the idea behind the BAOS modules is to abstract the whole KNX network behind it. Working with the BAOS protocol the user does not need to know about group addresses and group objects and all the other internals of the KNX network. From his point of view, there's a set of objects and they can be written or read. How these objects are mapped to the KNX world is determined within the ETS. Following this idea, there's no API function to retrieve the group addresses of a device.

Kind regards
