### ISSUE TITLE
Arduino compatibility

### ISSUE THREAD

**Issue by arangu97** [weinzierl-engineering/baos#15]
Hello,

Is there a way to integrate this SDK in Arduino code with an ESP32?

I have some Weinzierl BAOS Modules, but I dont know if I could use this SDK.

Thank you.

**Comment by weinzierl-engineering** [comment]
Hello arangu97,
currently Weinzierl Engineering GmbH does not offer any Arduino products or code samples.
You maybe can use this C++ library as a base for your own Arduino programming.
At the moment there is no Arduino example code available.
Best regards,
Weinzierl Engineering GmbH
