### ISSUE TITLE
c++ example to control group address

### ISSUE THREAD

**Issue by phantom-j** [weinzierl-engineering/baos#22]
I am using knx usb module 322.

Any example how to control (for starting just on/off) by using this sdk.

I didn't find any examples or documentation for kdrive c/c++ api .

Thank you

**Comment by weinzierl-engineering** [comment]
The sample_BaisLightSwichter just shows that. But repo has nothing to do with kdrive or its API. The BAOS SDK API documentation on the other hand is part of this repo.
