### ISSUE TITLE
Mac OS ARM Support

### ISSUE THREAD

**Issue by lecndav** [weinzierl-engineering/baos#27]
Hi,

is Mac OS with ARM currently supported?

**Comment by weinzierl-engineering** [comment]
The SDK was never build and tested on Mac OS with ARM. 
Although it should be possible in theory, we cannot provide any further information.

**Comment by lecndav** [comment]
I see. The biggest issue I think is that the USB and HID implementation is not supported. Either use a cross platform implementation or a device specific one. Other than that there should be no problem I guess.
