### ISSUE TITLE
Timeout: PEI_Identify.Con missing

### ISSUE THREAD

**Issue by ferrim** [weinzierl-engineering/baos#7]
Hello,
please I have some trouble with baos compiled on Raspberry pi 3b+ and 830 Knx module.
This is the console output:
(1st attempt)
pi@raspberrypi:~ $ sudo ./baos/build_unix/bin/sample_BaosSerial
16:00:30:089 [] Console Logger Started
16:00:34:492 [kdrive.connector.CallbackThread] Callback thread timeout stop sync [id 2, name QueueConnector Rx]
16:00:39:493 [kdrive.connector.CallbackThread] Unable to join thread [id 2, name QueueConnector Rx]
16:00:39:493 [kdrive.connector.Connector] Open failed: Timeout: PEI_Identify.Con missing
16:00:39:594 [BaosSerial] Timeout: PEI_Identify.Con missing

(relaunch)
pi@raspberrypi:~ $ sudo ./baos/build_unix/bin/sample_BaosSerial
16:26:30:218 [] Console Logger Started
16:26:30:611 [FT12_Packetizer] Variable length frame checksum failed
16:26:32:731 [kdrive.connector.Connector] Open failed: Timeout: PEI_Identify.Con missing
16:26:32:831 [BaosSerial] Timeout: PEI_Identify.Con missing

(relaunch)
pi@raspberrypi:~ $ sudo ./baos/build_unix/bin/sample_BaosSerial
16:27:02:185 [] Console Logger Started
16:27:05:603 [kdrive.connector.Connector] Open failed: Timeout: PEI_Identify.Con missing
16:27:05:704 [BaosSerial] Timeout: PEI_Identify.Con missing

any hints will be appreciated
Marcello

**Comment by weinzierl-engineering** [comment]
Please have look at https://github.com/weinzierl-engineering/baos/blob/master/docs/Raspbian.adoc into section kBerry to get a description how to configure the UART on newer raspberries.

Best regards,
Karl-Heinz

**Comment by ferrim** [comment]
Great support, thanks!

**Comment by Flachzange** [comment]
@ferrim Did you solve the issue and if how? I am bit lost with my new kBerry 838 module. The UART serial connection is definitely working but I cannot get the 838 working. As you I get 

09:03:09:690 [] Console Logger Started
09:03:13:113 [kdrive.connector.Connector] Open failed: Timeout: PEI_Identify.Con missing
09:03:13:213 [BaosSerial] Timeout: PEI_Identify.Con missing
